name: fedscale
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # PyTorch CPU builds
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  # TensorFlow CPU build
  - tensorflow=2.14.0
  - keras=2.14.0
  - tensorboard
  - numba
  - pandas
  - scipy>=1.7,<1.10
  - matplotlib>=3.1,<4
  - pillow
  - h5py
  - grpcio
  - sox
  - pytest
  - jupyter
  - PyYAML
  - sentencepiece
  - wandb
  - gym
  - pip
  - pip:
      - torch_optimizer
      - transformers
      - tensorboardX
      - overrides
      - python-levenshtein
      - gdown
      - librosa>=0.9.2
      - SoundFile
      - resampy
      - kubernetes