# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU process)
ps_ip: 129.104.252.43

# ip address of each worker:# of available gpus process on each gpu in this node
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips:
    - 129.104.252.43:[3]
    - 129.104.252.38:[4]
    - 129.104.252.39:[4]
    - 129.104.252.34:[4]
    - 129.104.252.32:[4]

exp_path: /users/eleves-a/2024/baptiste.geisenberger/FedScale/fedscale/cloud

# Entry function of executor and aggregator under $exp_path
executor_entry: execution/executor.py

aggregator_entry: aggregation/aggregator.py

auth:
    ssh_user: "baptiste.geisenberger"
    ssh_private_key: "/users/eleves-a/2024/baptiste.geisenberger/.ssh/id_rsa"

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - source /Data/baptiste.geisenberger/miniconda3/bin/activate fedscale

# ========== Additional job configuration ========== 
# Default parameters are specified in config_parser.py, wherein more description of the parameter can be found

job_conf:
    - job_name: stackoverflow
    - task: nlp
    - log_path: /users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark
    - data_set: blog
    - data_dir: /Data/baptiste.geisenberger/Data/stackoverflow
    - data_map_file: /Data/baptiste.geisenberger/Data/stackoverflow/client_data_mapping/result.csv
    - block_size: 64
    - clients_file: /users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark/dataset/data/clients.pkl
    - use_cuda: True
    - num_loaders: 1
    - clock_factor: 30
    - checkpoint_interval: 30
    - resume_from: "/users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark/logs/stackoverflow/ /checkpoints"

    - model: albert-base-v2
    - gradient_policy: fed-prox
    - proxy_mu: 0.001

    - num_participants: 100
    - eval_interval: 10
    - rounds: 500
    - local_steps: 30
    - batch_size: 32
    - filter_less: 32
    - learning_rate: 4e-5
    - decay_factor: 0.98
    - decay_round: 10
    - min_learning_rate: 2e-5
    - weight_decay: 0.01
    - test_bsz: 32
    - test_ratio: 0.25
    - overcommitment: 1.1

    - sample_mode: bliss
    - adaptive_training: True
    - run_phase_2: False

    - ema_alpha: 0.9
    - huber_delta: 2000
    - utility_ema_alpha: 0.6
    - recency_weighting_gamma: 0.015
    - sampling_temperature_eta: 1.5

    - t_budget: 275
    - pacer_step: 20
    - pacer_delta: 10

    - g_model: xgboost
    - xgboost_g_n_estimators: 200
    - xgboost_g_learning_rate: 0.02
    - xgboost_g_max_depth: 6
    - xgboost_g_subsample: 0.7
    - xgboost_g_colsample_bytree: 0.7

    - h_model: xgboost
    - xgboost_h_n_estimators: 200
    - xgboost_h_learning_rate: 0.05
    - xgboost_h_max_depth: 3
    - xgboost_h_subsample: 0.7
    - xgboost_h_colsample_bytree: 1.0
